# This is very specific to my deployment.
# For running the whole application with database, use /local/docker-compose.full.yaml file.
services:
  personals:
    container_name: Personals
    hostname: personals
    image: ghcr.io/sathiyaraman-m/personals:latest
    restart: unless-stopped
    ports:
      - "7005:80"
    volumes:
      - "./appsettings.json:/app/appsettings.json"
    environment:
      ASPNETCORE_URLS: http://+:80
    networks:
      - personals

networks:
  personals:
    name: personals-shared-network
    external: true